Repository StepUpper/stepup_front, pull requests merged in 2024-11, with the labels that each got.

#150 feat: Add Google Login #50
  frontend/src/apis/firebase/auth.ts
  frontend/src/components/Chat/ChatLogin.tsx
Labels: ✨ Feature, 🔨 Refactor

#148 feat: 신발장 상태 전역 관리 및 임시저장 여부 분기처리
  frontend/.pnp.cjs
  frontend/.pnp.loader.mjs
  frontend/.yarn/cache/react-webcam-npm-7.2.0-4404f3658d-d639a9e4cd.zip
  frontend/src/components/common/Header.tsx
  frontend/src/components/shoeCloset/AddShoeButton.tsx
  frontend/src/components/shoeCloset/EmptyShoeCard.tsx
  frontend/src/components/shoeCloset/ShoeClosetResumeDraftModal.tsx
  frontend/src/components/shoeCloset/ShoeClosetSaveDraftModal.tsx
  frontend/src/components/shoeCloset/details/ShoeClosetOptionMenu.tsx
  frontend/src/components/shoeCloset/register/RecomendSizeRadioGroup.tsx
  frontend/src/components/shoeCloset/register/SelectedShoe.tsx
  frontend/src/components/shoeCloset/register/ShoeRegisterInputForm.tsx
  frontend/src/components/shoeCloset/search/ImageSearch/ShoeImageSearchResult.tsx
  frontend/src/components/shoeCloset/search/ImageSearch/SimilarShoeList.tsx
  frontend/src/components/shoeCloset/search/SearchResultItem.tsx
  frontend/src/components/shoeCloset/search/SearchResultList.tsx
  frontend/src/components/shoeCloset/search/TextShoeSearch.tsx
  frontend/src/pages/MyShopping/MyShopping.tsx
  frontend/src/pages/ShoeCloset/SearchShoeCloset.tsx
  frontend/src/pages/ShoeCloset/ShoeCloset.tsx
  frontend/src/pages/ShoeCloset/ShoeClosetAdd.tsx
  frontend/src/pages/ShoeCloset/ShoeClosetDetail.tsx
  frontend/src/pages/ShoeCloset/ShoeClosetModify.tsx
  frontend/src/store/review.store.ts
  frontend/src/store/selectedShoe.store.ts
Labels: ✨ Feature, 🔨 Refactor, 우선순위: 🟠 높음, 🙋‍♂️ Question

#152 비슷한 상품 더보기에서 선택된 상품 등록되도록 수정
  frontend/src/components/shoeCloset/search/ImageSearch/ShoeImageSearchResult.tsx
  frontend/src/components/shoeCloset/search/ImageSearch/SimilarShoeList.tsx
Labels: 🐞 BugFix, 우선순위: 🔴 긴급
