Repository StepUpper/stepup_front, pull requests merged in 2024-09, with the labels that each got.

#11 Resolves: 커스텀 버튼 컴포넌트 생성 #8
  frontend/src/components/common/BottomButton.tsx
  frontend/src/components/common/Input.tsx
  frontend/src/components/common/OptionSelectorButton.tsx
  frontend/src/components/common/html/Button.tsx
Labels: ✨ Feature, 🎨 Html&css, 우선순위: 🟠 높음

#10 #4 공통 컴포넌트 입력 필드 생성
  frontend/src/components/common/InputField.tsx
  frontend/src/components/common/html/Input.tsx
Labels: ✨ Feature, 🎨 Html&css, 우선순위: 🟠 높음

#16 feat: 공통 dropdown 컴포넌트 생성
  frontend/src/assets/dropdownIcon.svg
  frontend/src/components/common/html/DropDown.tsx
  frontend/src/components/common/html/Input.tsx
Labels: ✨ Feature, 🎨 Html&css, 우선순위: 🟠 높음

#17 공통 Header와 카테고리별 버튼 컴포넌트 생성
  frontend/src/assets/assets.ts
  frontend/src/assets/images/back-icon.svg
  frontend/src/assets/images/kebab-icon.svg
  frontend/src/assets/images/menu-icon.svg
  frontend/src/components/common/CategorySelector.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/styles/tailwind.css
Labels: ✨ Feature, 🎨 Html&css, 우선순위: 🟠 높음

#19 공통 레이아웃 스타일 설정, 404페이지 생성과 라우터 처리
  frontend/src/App.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/pages/NotFound/NotFound.tsx
  frontend/src/router/index.tsx
Labels: ✨ Feature, 🎨 Html&css, 우선순위: 🟡 중간

#22 Resolves: 채팅방 header,footer생성, icon 관리, db연동 #14
  frontend/.gitignore
  frontend/src/assets/assets.ts
  frontend/src/assets/images/arrow-up-icon.svg
  frontend/src/assets/images/drop-down-icon.svg
  frontend/src/assets/images/image-select-icon.svg
  frontend/src/assets/images/touch-box-icon.svg
  frontend/src/components/common/html/DropDown.tsx
  frontend/src/components/common/html/Input.tsx
  frontend/src/firebase.ts
  frontend/src/pages/Chat/ChatHeader.tsx
  frontend/src/pages/Chat/ChatInput.tsx
Labels: ⚙ Setting, ✨ Feature, 🎨 Html&css, 우선순위: 🟠 높음

#26 회원가입 정보 입력받는 컴포넌트 생성
  frontend/src/assets/assets.ts
  frontend/src/assets/images/info-icon.svg
  frontend/src/components/common/OptionSelectorButton.tsx
  frontend/src/components/common/html/DropDown.tsx
  frontend/src/components/common/html/Input.tsx
  frontend/src/components/login/Login.tsx
  frontend/src/components/signup/SignUp.tsx
  frontend/src/components/signup/SignUpAdditional.tsx
  frontend/src/components/signup/SignUpRequired.tsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor, 우선순위: 🟠 높음, 🙋‍♂️ Question

#39 Bottom Sheet 생성
  frontend/.pnp.cjs
  frontend/.yarn/cache/framer-motion-npm-11.5.4-2c83cdc870-2405aad0ed.zip
  frontend/package.json
  frontend/src/assets/assets.ts
  frontend/src/assets/images/bar-icon.svg
  frontend/src/assets/images/foot-loading.webp
  frontend/src/components/common/BottomButton.tsx
  frontend/src/components/common/BottomSheet.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/myFootInfo/FootInfoPlaceholder.tsx
  frontend/src/hooks/useBottomSheet.tsx
  frontend/src/styles/tailwind.css
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: ✨ Feature, 🎨 Html&css, 💻 CrossBrowsing, 우선순위: 🟠 높음

#32 feat: Mypage 페이지 생성
  frontend/src/assets/assets.ts
  frontend/src/assets/images/camera-icon.svg
  frontend/src/assets/images/chat-list-icon.svg
  frontend/src/assets/images/chevron-right-icon.svg
  frontend/src/assets/images/default-profile-img.svg
  frontend/src/assets/images/like-stroke-icon.svg
  frontend/src/assets/images/plus-icon.svg
  frontend/src/assets/images/share-white-icon.svg
  frontend/src/assets/images/smile-icon.svg
  frontend/src/assets/images/trash-icon.svg
  frontend/src/components/Chat/ChatInput.tsx
  frontend/src/components/Chat/ChatMessage.tsx
  frontend/src/components/common/ProfileImage.tsx
  frontend/src/components/myshopping/LikedBrands.tsx
  frontend/src/components/myshopping/LikedItems.tsx
  frontend/src/components/myshopping/RecentItems.tsx
  frontend/src/components/sidemenu/SideChatListItem.tsx
  frontend/src/components/sidemenu/SideMenu.tsx
  frontend/src/components/signup/SignUpAdditional.tsx
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/pages/MyShopping/MyShopping.tsx
  frontend/src/router/index.tsx
Labels: ✨ Feature, 우선순위: 🟠 높음

#40 feat: 신발장 페이지 /신발리스트, /신발등록 페이지 생성
  frontend/src/assets/assets.ts
  frontend/src/assets/images/archive/default-profile-image.svg
  frontend/src/assets/images/icons/arrow-up-icon.svg
  frontend/src/assets/images/icons/back-icon.svg
  frontend/src/assets/images/icons/drop-down-icon.svg
  frontend/src/assets/images/icons/image-select-icon.svg
  frontend/src/assets/images/icons/info-icon.svg
  frontend/src/assets/images/icons/kebab-icon.svg
  frontend/src/assets/images/icons/like-icon.svg
  frontend/src/assets/images/icons/menu-icon.svg
  frontend/src/assets/images/icons/perfitt-logo.svg
  frontend/src/assets/images/icons/plus-icon.svg
  frontend/src/assets/images/icons/share-icon.svg
  frontend/src/assets/images/icons/shoe-search.svg
  frontend/src/assets/images/icons/show-brand-product-icon.svg
  frontend/src/assets/images/icons/sort-icon.svg
  frontend/src/assets/images/icons/star-filled-icon.svg
  frontend/src/assets/images/icons/star-icon.svg
  frontend/src/assets/images/icons/thumbs-down-icon.svg
  frontend/src/components/common/BottomButton.tsx
  frontend/src/components/shoe_closet/AddShoeButton.tsx
  frontend/src/components/shoe_closet/EmptyShoeCard.tsx
  frontend/src/components/shoe_closet/EmptyShoeComponent.tsx
  frontend/src/components/shoe_closet/ProfileCard.tsx
  frontend/src/components/shoe_closet/ShoeComponent.tsx
  frontend/src/components/shoe_closet/ShoeListComponent.tsx
  frontend/src/components/shoe_closet/register/RatingComponent.tsx
  frontend/src/components/shoe_closet/register/RecomendSizeRadioGroup.tsx
  frontend/src/components/shoe_closet/register/ReviewOptionSelectorButton.tsx
  frontend/src/components/shoe_closet/register/SearchShoeButton.tsx
  frontend/src/components/shoe_closet/register/ShoeRegisterInputForm.tsx
  frontend/src/components/shoe_closet/register/SubmitBottomButton.tsx
  frontend/src/hooks/useInput.ts
  frontend/src/pages/Review/page.tsx
  frontend/src/pages/ShoeCloset/page.tsx
  frontend/src/router/index.tsx
Labels: ✨ Feature, 🎨 Html&css, 우선순위: 🟡 중간

#48 Feat: 로그인 상태에서의 채팅 로직 구성
  frontend/src/apis/firebase/likeFirestore.ts
  frontend/src/components/Chat/ChatInput.tsx
  frontend/src/components/Chat/ChatMessage.tsx
  frontend/src/components/Chat/ChatProductItem.tsx
  frontend/src/components/Chat/ChatRecommendedQuestion.tsx
  frontend/src/components/common/html/Input.tsx
  frontend/src/pages/Chat/Chat.tsx
  frontend/src/types/chat.d.ts
Labels: ✨ Feature, 📬 API, 우선순위: 🟠 높음

#46 내 발 측정하기 sdk 연결 및 페이지 라우터 처리
  frontend/eslint.config.js
  frontend/index.html
  frontend/src/components/common/Header.tsx
  frontend/src/components/myFootInfo/FootInfoDisplay.tsx
  frontend/src/pages/MyFootInfo/MyFootInfo.tsx
  frontend/src/router/index.tsx
Labels: ⚙ Setting, ✨ Feature, 📬 API, 우선순위: 🟠 높음

#47 Feat: auth 기능 추가 #35
  frontend/src/apis/firebase/auth.ts
  frontend/src/components/Chat/ChatLogin.tsx
  frontend/src/components/common/OptionSelectorButton.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/login/Login.tsx
  frontend/src/components/login/LoginBottomSheet.tsx
  frontend/src/components/signup/SignUp.tsx
  frontend/src/components/signup/SignUpAdditional.tsx
  frontend/src/components/signup/SignUpRequired.tsx
  frontend/src/firebase.ts
  frontend/src/pages/Chat/Chat.tsx
  frontend/src/router/index.tsx
  frontend/src/router/loaders/onBoading.ts
  frontend/src/store/auth.store.ts
  frontend/src/types/auth.d.ts
Labels: ✨ Feature, 우선순위: 🟠 높음

#52 바텀시트 전역관리로 변경과 브랜드 PLP, 브릿지 구현
  frontend/src/apis/services/chat.ts
  frontend/src/apis/services/plp.ts
  frontend/src/assets/assets.ts
  frontend/src/assets/icons/close-icon.svg
  frontend/src/assets/icons/filter-icon.svg
  frontend/src/assets/icons/select-arrow-icon.svg
  frontend/src/assets/images/ai-icon-img.png
  frontend/src/components/common/BottomButton.tsx
  frontend/src/components/common/BottomSheet.tsx
  frontend/src/components/common/CategorySelector.tsx
  frontend/src/components/common/LikeButton.tsx
  frontend/src/components/common/ProductItem.tsx
  frontend/src/components/common/ProductLearnMoreButton.tsx
  frontend/src/components/common/ProductList.tsx
  frontend/src/components/myshopping/LikedItems.tsx
  frontend/src/components/plp/BrandPLPPanel.tsx
  frontend/src/components/plp/FilterPanel.tsx
  frontend/src/components/plp/GenderCategorySelector.tsx
  frontend/src/components/plp/PLPControls.tsx
  frontend/src/components/plp/PLPEmptyList.tsx
  frontend/src/components/plp/PLPHeader.tsx
  frontend/src/constants/categories.ts
  frontend/src/pages/Bridge/Bridge.tsx
  frontend/src/router/index.tsx
  frontend/src/store/bottomSheet.store.ts
  frontend/src/types/plp.d.ts
  frontend/tsconfig.paths.json
Labels: ✨ Feature, 🎨 Html&css, 📬 API, 🔨 Refactor, 우선순위: 🟠 높음

#54 feat: 로그인 상태 전역 관리 #42
  frontend/src/components/Chat/ChatInput.tsx
  frontend/src/components/Chat/ChatRecommendedQuestion.tsx
  frontend/src/components/login/LoginBottomSheet.tsx
  frontend/src/pages/Chat/Chat.tsx
  frontend/src/store/chat.store.ts
  frontend/vite.config.ts.timestamp-1726118168958-72b48cc9a5d27.mjs
  frontend/vite.config.ts.timestamp-1726118323177-f846f4c053c1e.mjs
Labels: ✨ Feature, 우선순위: 🟠 높음

#53 사이드메뉴 토글 추가 및 채팅 리스트 스와이프 수정, 마이쇼핑 페이지 내 컴포넌트 구현
  frontend/src/components/common/Header.tsx
  frontend/src/components/myshopping/LikedBrands.tsx
  frontend/src/components/myshopping/LikedItems.tsx
  frontend/src/components/myshopping/RecentItems.tsx
  frontend/src/components/sidemenu/SideChatListItem.tsx
  frontend/src/components/sidemenu/SideMenu.tsx
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/pages/MyShopping/MyShopping.tsx
  frontend/src/router/index.tsx
Labels: ✨ Feature, 🐞 BugFix, 우선순위: 🟠 높음

#55 feat : 클릭된 brand, products 전역으로 관리 #45
  frontend/src/components/Chat/ChatMessage.tsx
  frontend/src/store/productAndBrand.store.ts
Labels: ✨ Feature, 우선순위: 🟠 높음

#56 로그인/회원가입 바텀 시트 상대 관리 수정과 오버레이 닫힘 기능 옵션으로 변경
  frontend/src/components/Chat/ChatLogin.tsx
  frontend/src/components/Chat/ChatMessage.tsx
  frontend/src/components/common/BottomSheet.tsx
  frontend/src/components/login/LoginBottomSheet.tsx
  frontend/src/hooks/useBottomSheet.tsx
  frontend/src/pages/Chat/Chat.tsx
Labels: 🔨 Refactor, 우선순위: 🟠 높음

#58 바텀 시트 관련 기능 개선 및 이벤트 처리 추가, 관심 키워드 생성
  frontend/src/components/Chat/ChatMessage.tsx
  frontend/src/components/Chat/InterestKeywordsBottomSheet.tsx
  frontend/src/components/common/BottomSheet.tsx
  frontend/src/components/login/LoginBottomSheet.tsx
  frontend/src/components/plp/BrandPLPBottomSheet.tsx
  frontend/src/components/plp/FilterBottomSheet.tsx
  frontend/src/components/signup/SignUpAdditional.tsx
  frontend/src/pages/Chat/Chat.tsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor, 우선순위: 🔴 긴급

#62 Feat: 회원가입 후 처리
  frontend/src/apis/firebase/chatFirestore.ts
  frontend/src/assets/assets.ts
  frontend/src/assets/icons/interest-check-icon.svg
  frontend/src/components/Chat/ChatBrandCard.tsx
  frontend/src/components/Chat/ChatInput.tsx
  frontend/src/components/Chat/ChatMessage.tsx
  frontend/src/components/Chat/ChatProductItem.tsx
  frontend/src/components/Chat/ChatRecommendedQuestion.tsx
  frontend/src/components/Chat/InterestKeywordsBottomSheet.tsx
  frontend/src/components/common/ProductLearnMoreButton.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/login/Login.tsx
  frontend/src/components/myshopping/LikedBrands.tsx
  frontend/src/components/myshopping/LikedItems.tsx
  frontend/src/components/plp/GenderCategorySelector.tsx
  frontend/src/components/sidemenu/SideMenu.tsx
  frontend/src/components/signup/SignUpAdditional.tsx
  frontend/src/pages/Bridge/Bridge.tsx
  frontend/src/pages/Chat/Chat.tsx
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/pages/MyShopping/MyShopping.tsx
Labels: ✨ Feature, 🐞 BugFix, 📬 API, 우선순위: 🟠 높음

#64 회원가입 바텀시트 내 드롭다운 수정, 마이쇼핑 라우터 변경
  frontend/src/components/common/html/DropDown.tsx
  frontend/src/components/signup/SignUpRequired.tsx
  frontend/src/router/index.tsx
Labels: 🐞 BugFix

#63 바텀 시트 기능 개선 및 에러 수정, 로그인 후 동작 추가
  frontend/src/components/common/BottomSheet.tsx
  frontend/src/components/common/ProductList.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/login/Login.tsx
  frontend/src/components/plp/BrandPLPBottomSheet.tsx
  frontend/src/components/plp/FilterBottomSheet.tsx
  frontend/src/components/plp/GenderCategorySelector.tsx
  frontend/src/pages/Chat/Chat.tsx
  frontend/src/store/bottomSheet.store.ts
Labels: ✨ Feature, 🔨 Refactor, 우선순위: 🟠 높음

#67 Feat: 로그인 시 맞춤상품 추천, 회원가입 시 관심키워드 설정 및 응답 호출
  frontend/src/components/Chat/ChatBrandCard.tsx
  frontend/src/components/Chat/ChatLogin.tsx
  frontend/src/components/Chat/ChatMessage.tsx
  frontend/src/components/Chat/ChatReqProdItem.tsx
  frontend/src/components/Chat/InterestKeywordsBottomSheet.tsx
  frontend/src/components/common/OptionSelectorButton.tsx
  frontend/src/components/login/Login.tsx
  frontend/src/components/signup/SignUpAdditional.tsx
  frontend/src/types/chat.d.ts
Labels: ✨ Feature, 🐞 BugFix, 📬 API, 우선순위: 🟠 높음

#69 PLP API 요청 처리 개선, 공통 PLP 컴포넌트로 통합 및 브랜드 PLP UI 분리
  frontend/src/apis/apis.ts
  frontend/src/apis/services/chat.ts
  frontend/src/apis/services/plp.ts
  frontend/src/components/common/Error.tsx
  frontend/src/components/plp/BrandPLP.tsx
  frontend/src/components/plp/BrandPLPBottomSheet.tsx
  frontend/src/components/plp/GenderCategorySelector.tsx
  frontend/src/components/plp/PLPBottomSheet.tsx
  frontend/src/components/plp/PLPControls.tsx
  frontend/src/hooks/useAxios.ts
  frontend/src/pages/Chat/Chat.tsx
Labels: ✨ Feature, 📬 API, 🔨 Refactor, 우선순위: 🟠 높음

#66 로그인된 유저 정보 받아와서 출력
  frontend/src/components/shoeCloset/ProfileCard.tsx
  frontend/src/components/sidemenu/SideMenu.tsx
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/router/index.tsx
Labels: 🔨 Refactor

#70 feat: signup additional에서 입력한 값 db에 저장#68
  frontend/src/components/signup/SignUpAdditional.tsx
Labels: 🐞 BugFix, 우선순위: 🟠 높음

#72 feat: 중간발표 전 markdown 디자인 수정
  frontend/src/components/Chat/ChatMessage.tsx
Labels: 🎨 Html&css, 우선순위: 🟡 중간

#75 feat: 더보기 버튼, 채팅에서 상품 좋아요, 새 채팅방 생성 #74
  frontend/src/apis/firebase/auth.ts
  frontend/src/apis/firebase/chatFirestore.ts
  frontend/src/apis/firebase/likeFirestore.ts
  frontend/src/assets/assets.ts
  frontend/src/assets/icons/arrow-right-icon.svg
  frontend/src/components/Chat/ChatMessage.tsx
  frontend/src/components/Chat/ChatProductItem.tsx
  frontend/src/components/common/LikeButton.tsx
  frontend/src/components/login/Login.tsx
  frontend/src/components/sidemenu/SideMenu.tsx
  frontend/src/pages/Chat/Chat.tsx
  frontend/src/store/auth.store.ts
  frontend/src/types/auth.d.ts
Labels: ✨ Feature, 📬 API, 우선순위: 🟠 높음

#80 fix: build 에러 해결
  frontend/src/components/common/Error.tsx
  frontend/src/components/common/ProductLearnMoreButton.tsx
  frontend/src/components/login/LoginBottomSheet.tsx
  frontend/src/components/myshopping/LikedItems.tsx
  frontend/src/components/plp/BrandPLP.tsx
  frontend/src/components/plp/FilterBottomSheet.tsx
  frontend/src/components/plp/PLPBottomSheet.tsx
  frontend/src/components/plp/PLPProductDisplay.tsx
  frontend/src/components/plp/ProductsPLP.tsx
  frontend/src/components/shoeCloset/register/ReviewOptionSelectorButton.tsx
  frontend/src/components/shoeCloset/register/SearchShoeButton.tsx
  frontend/src/components/shoeCloset/register/ShoeRegisterInputForm.tsx
  frontend/src/components/shoeCloset/register/SubmitBottomButton.tsx
  frontend/src/components/sidemenu/SideChatListItem.tsx
  frontend/src/components/sidemenu/SideMenu.tsx
  frontend/src/hooks/useAxios.ts
  frontend/src/pages/MyFootInfo/MyFootInfo.tsx
  frontend/tsconfig.paths.json
Labels: 🐞 BugFix

#82 공유 모달에 필요한 data 전달
  frontend/src/apis/firebase/chatFirestore.ts
  frontend/src/assets/assets.ts
  frontend/src/assets/icons/chat-circle-icon.svg
  frontend/src/assets/icons/copy-left-icon.svg
  frontend/src/assets/icons/link-angled-icon.svg
  frontend/src/assets/icons/loading-icon.svg
  frontend/src/components/Chat/ChatInput.tsx
  frontend/src/components/Chat/ChatMessage.tsx
  frontend/src/components/Chat/ChatProductItem.tsx
  frontend/src/components/Chat/ChatRecommendedQuestion.tsx
  frontend/src/components/Chat/ChatShareDislikeBox.tsx
  frontend/src/components/Chat/ChatShareModal.tsx
  frontend/src/components/Chat/InterestKeywordsBottomSheet.tsx
  frontend/src/components/common/LikeButton.tsx
  frontend/src/components/signup/SignUpAdditional.tsx
  frontend/src/pages/Chat/Chat.tsx
  frontend/src/store/chat.store.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API, 우선순위: 🟠 높음

#85 사이드메뉴 채팅방 목록 뿌리기, 로그아웃 기능 추가, 마이쇼핑 페이지에 좋아요 상품 불러오기
  frontend/src/assets/assets.ts
  frontend/src/assets/images/shoeHeart.svg
  frontend/src/components/common/Logout.tsx
  frontend/src/components/myshopping/LikedBrands.tsx
  frontend/src/components/myshopping/LikedItems.tsx
  frontend/src/components/sidemenu/SideMenu.tsx
Labels: ✨ Feature, 🔨 Refactor

#86 사이드메뉴 타입에러 해결
  frontend/src/assets/assets.ts
  frontend/src/components/sidemenu/SideMenu.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#90 feat: 공유하기
  frontend/src/apis/firebase/chatFirestore.ts
  frontend/src/apis/firebase/likeFirestore.ts
  frontend/src/components/Chat/ChatMessage.tsx
  frontend/src/components/Chat/ChatProductItem.tsx
  frontend/src/components/Chat/ChatShareDislikeBox.tsx
  frontend/src/components/Chat/ChatShareModal.tsx
  frontend/src/components/Chat/ChatShareView.tsx
  frontend/src/components/login/Login.tsx
  frontend/src/router/index.tsx
  frontend/src/store/auth.store.ts
  frontend/src/store/chat.store.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API, 우선순위: 🟠 높음

#93 plp/마이페이지 좋아요 기능 추가 및 개선, 발사이즈 변환, css 수정
  frontend/src/apis/firebase/likeFirestore.ts
  frontend/src/assets/assets.ts
  frontend/src/assets/images/shoe-img.png
  frontend/src/components/common/Error.tsx
  frontend/src/components/common/ProductList.tsx
  frontend/src/components/common/html/Img.tsx
  frontend/src/components/myFootInfo/FootInfoPlaceholder.tsx
  frontend/src/components/myshopping/LikedItems.tsx
  frontend/src/components/plp/PLPEmptyList.tsx
  frontend/src/components/plp/PLPProductDisplay.tsx
  frontend/src/components/plp/ProductsPLP.tsx
  frontend/src/hooks/useSizeConversion.ts
  frontend/src/pages/Bridge/Bridge.tsx
  frontend/src/pages/MyFootInfo/MyFootInfo.tsx
  frontend/src/store/auth.store.ts
  frontend/src/types/plp.d.ts
Labels: ✨ Feature, 🔨 Refactor, 우선순위: 🟠 높음

#95 feat: 공유하기 마무리, 채팅방 개설
  frontend/src/apis/firebase/chatFirestore.ts
  frontend/src/apis/firebase/likeFirestore.ts
  frontend/src/components/Chat/ChatMessage.tsx
  frontend/src/components/Chat/ChatShareModal.tsx
  frontend/src/components/Chat/ChatShareView.tsx
  frontend/src/components/sidemenu/SideChatListItem.tsx
  frontend/src/components/sidemenu/SideMenu.tsx
  frontend/src/pages/Chat/Chat.tsx
  frontend/src/store/chat.store.ts
Labels: ✨ Feature, 📬 API, 우선순위: 🟠 높음

#100 feat : 상품 데이터 값 통일 작업
  frontend/src/apis/firebase/likeFirestore.ts
  frontend/src/components/Chat/ChatMessage.tsx
  frontend/src/components/Chat/ChatProductItem.tsx
  frontend/src/components/common/ProductList.tsx
  frontend/src/components/myshopping/LikedItems.tsx
  frontend/src/store/auth.store.ts
  frontend/src/utils/storeRecentProducts.ts
Labels: ✨ Feature, 📬 API, 우선순위: 🟠 높음

#101 PLP 개선, 바텀 시트 상태 유지, 상품 데이터 통일 및 기타 수정
  frontend/src/apis/firebase/chatFirestore.ts
  frontend/src/apis/firebase/likeFirestore.ts
  frontend/src/assets/assets.ts
  frontend/src/components/Chat/ChatMessage.tsx
  frontend/src/components/Chat/ChatProductItem.tsx
  frontend/src/components/Chat/ChatShareModal.tsx
  frontend/src/components/common/BottomButton.tsx
  frontend/src/components/common/BottomSheet.tsx
  frontend/src/components/common/Error.tsx
  frontend/src/components/common/ProductList.tsx
  frontend/src/components/common/Skeleton.tsx
  frontend/src/components/common/html/Button.tsx
  frontend/src/components/common/html/DropDown.tsx
  frontend/src/components/common/html/Img.tsx
  frontend/src/components/login/Login.tsx
  frontend/src/components/myFootInfo/FootInfoPlaceholder.tsx
  frontend/src/components/plp/BrandPLP.tsx
  frontend/src/components/plp/FilterBottomSheet.tsx
  frontend/src/components/plp/GenderCategorySelector.tsx
  frontend/src/components/plp/PLPBottomSheet.tsx
  frontend/src/components/plp/PLPHeader.tsx
  frontend/src/components/plp/PLPLoading.tsx
  frontend/src/components/plp/PLPProductDisplay.tsx
  frontend/src/components/plp/ProductsPLP.tsx
  frontend/src/components/signup/SignUpRequired.tsx
  frontend/src/hooks/useFocus.ts
  frontend/src/pages/Bridge/Bridge.tsx
  frontend/src/pages/Chat/Chat.tsx
  frontend/src/types/plp.d.ts
  frontend/src/types/product.d.ts
  frontend/src/utils/storeRecentProducts.ts
Labels: 🔨 Refactor, 우선순위: 🔴 긴급

#103 내 정보 수정, 비밀번호 변경 ui 작업 그 외
  frontend/src/assets/assets.ts
  frontend/src/assets/icons/chat-circle-icon.svg
  frontend/src/assets/icons/chat-filled-icon.svg
  frontend/src/components/Chat/ChatShareModal.tsx
  frontend/src/components/Chat/ChatShareView.tsx
  frontend/src/components/common/ProductList.tsx
  frontend/src/components/mypage/ChangePassword.tsx
  frontend/src/components/mypage/CheckPassword.tsx
  frontend/src/components/mypage/EditUserInfo.tsx
  frontend/src/components/myshopping/LikedBrands.tsx
  frontend/src/components/myshopping/LikedProducts.tsx
  frontend/src/components/myshopping/RecentProducts.tsx
  frontend/src/components/sidemenu/SideChatListItem.tsx
  frontend/src/components/sidemenu/SideMenu.tsx
  frontend/src/pages/ChangePassword/ChangePasswordPage.tsx
  frontend/src/pages/EditUserInfo/EditUserInfoPage.tsx
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/pages/MyShopping/MyShopping.tsx
  frontend/src/router/index.tsx
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor, 우선순위: 🔴 긴급

#105 feat: markdown 디자인 수정, 새채팅 누르면 채팅기록 초기화
  frontend/src/components/Chat/ChatMessage.tsx
  frontend/src/components/myshopping/LikedProducts.tsx
  frontend/src/components/sidemenu/SideMenu.tsx
Labels: 🎨 Html&css, 🐞 BugFix, 우선순위: 🟠 높음

#108 feat : 채팅방 삭제, 현재 속한 채팅방 표시 #107
  frontend/src/apis/firebase/chatFirestore.ts
  frontend/src/components/sidemenu/SideMenu.tsx
Labels: ✨ Feature, 📬 API, 우선순위: 🟠 높음

#110 채팅방 삭제, 현재 속한 채팅방 표시
  frontend/src/apis/firebase/chatFirestore.ts
  frontend/src/components/sidemenu/SideMenu.tsx
Labels: ✨ Feature, 우선순위: 🟠 높음

#111 채팅방 삭제, 현재 속한 채팅방 표시
  frontend/src/apis/firebase/chatFirestore.ts
  frontend/src/components/sidemenu/SideMenu.tsx
Labels: ✨ Feature

#115 사파리에서 로그인/회원가입 바텀이 처음 열릴때 최상단 위로 올라갔다가 내려오는 현상 해결
  frontend/src/hooks/useFocus.ts
  frontend/src/pages/Chat/Chat.tsx
Labels: 🐞 BugFix, 💻 CrossBrowsing, 🔨 Refactor, 우선순위: 🔴 긴급

#116 사파리에서 로그인/회원가입 바텀이 처음 열릴때 최상단 위로 올라갔다가 내려오는 현상 해결
  frontend/src/hooks/useFocus.ts
  frontend/src/pages/Chat/Chat.tsx
Labels: 🐞 BugFix, 💻 CrossBrowsing, 🔨 Refactor, 우선순위: 🔴 긴급
