Repository StepUpper/stepup_front, pull requests merged in 2024-10, with the labels that each got.

#118 채팅 상단에 현재 가능한 질문 목록 추가 및 useAxios 개선
  frontend/src/apis/services/chat.ts
  frontend/src/assets/assets.ts
  frontend/src/assets/icons/notice-icon.png
  frontend/src/components/Chat/ChatSampleQuestions.tsx
  frontend/src/components/plp/BrandPLP.tsx
  frontend/src/hooks/useAxios.ts
  frontend/src/pages/Chat/Chat.tsx
Labels: 🔨 Refactor, 우선순위: 🟠 높음

#119 리드미 수정과 채팅 상단에 현재 가능한 질문 목록 추가 및 useAxios 개선
  README.md
  frontend/src/apis/services/chat.ts
  frontend/src/assets/assets.ts
  frontend/src/assets/icons/notice-icon.png
  frontend/src/components/Chat/ChatSampleQuestions.tsx
  frontend/src/components/plp/BrandPLP.tsx
  frontend/src/hooks/useAxios.ts
  frontend/src/pages/Chat/Chat.tsx
Labels: 🔨 Refactor, 우선순위: 🟡 중간

#127 feat: 신발장 신발 등록 및 업데이트 함수 구현 #122
  frontend/src/apis/firebase/auth.ts
  frontend/src/apis/firebase/closetFirestore.ts
  frontend/src/store/auth.store.ts
Labels: ✨ Feature, 📬 API, 우선순위: 🟡 중간

#129 feat: 신발장 텍스트 검색 기능 구현
  frontend/src/apis/services/chat.ts
  frontend/src/apis/services/shoeSearch.ts
  frontend/src/assets/assets.ts
  frontend/src/assets/icons/search-icon.svg
  frontend/src/components/common/BottomButton.tsx
  frontend/src/components/shoeCloset/ShoeComponent.tsx
  frontend/src/components/shoeCloset/ShoeListComponent.tsx
  frontend/src/components/shoeCloset/register/SearchShoeButton.tsx
  frontend/src/components/shoeCloset/register/SelectedShoe.tsx
  frontend/src/components/shoeCloset/search/RecentTextSearches.tsx
  frontend/src/components/shoeCloset/search/SearchResultList.tsx
  frontend/src/components/shoeCloset/search/TextShoeSearch.tsx
  frontend/src/pages/Review/Review.tsx
  frontend/src/pages/Review/page.tsx
  frontend/src/pages/ShoeCloset/SearchShoeCloset.tsx
  frontend/src/pages/ShoeCloset/ShoeCloset.tsx
  frontend/src/router/index.tsx
  frontend/src/types/product.d.ts
  frontend/src/utils/storeRecentSearches.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API, 우선순위: 🟠 높음

#130 feat: 신발장 등록 기능 구현
  frontend/src/assets/assets.ts
  frontend/src/assets/icons/pencil-icon.svg
  frontend/src/assets/icons/share-black-icon.svg
  frontend/src/assets/icons/trash-red-icon.svg
  frontend/src/assets/images/shoe-eye.svg
  frontend/src/assets/images/shoe-heart.svg
  frontend/src/assets/images/shoe-img.png
  frontend/src/assets/images/shoe-img.svg
  frontend/src/components/common/Header.tsx
  frontend/src/components/shoeCloset/ShoeComponent.tsx
  frontend/src/components/shoeCloset/ShoeListComponent.tsx
  frontend/src/components/shoeCloset/details/ShoeClosetDetailInfo.tsx
  frontend/src/components/shoeCloset/details/ShoeClosetMainInfo.tsx
  frontend/src/components/shoeCloset/details/ShoeClosetOptionMenu.tsx
  frontend/src/components/shoeCloset/details/ShoeClosetThumb.tsx
  frontend/src/components/shoeCloset/register/RatingComponent.tsx
  frontend/src/components/shoeCloset/register/RecomendSizeRadioGroup.tsx
  frontend/src/components/shoeCloset/register/ShoeRegisterInputForm.tsx
  frontend/src/components/shoeCloset/register/SubmitBottomButton.tsx
  frontend/src/components/shoeCloset/search/RecentTextSearches.tsx
  frontend/src/pages/Review/Review.tsx
  frontend/src/pages/ShoeCloset/ShoeCloset.tsx
  frontend/src/pages/ShoeCloset/ShoeClosetOverview.tsx
  frontend/src/router/index.tsx
Labels: ✨ Feature, 우선순위: 🟠 높음, 🙋‍♂️ Question

#134 상품 리스트 무한스크롤 적용 및 productItem 컴포넌트 분리
  frontend/package.json
  frontend/src/components/Chat/ChatSampleQuestions.tsx
  frontend/src/components/common/BottomSheet.tsx
  frontend/src/components/common/ProductItem.tsx
  frontend/src/components/common/ProductList.tsx
  frontend/src/components/myshopping/LikedProducts.tsx
  frontend/src/components/myshopping/RecentProducts.tsx
  frontend/src/components/plp/BrandPLP.tsx
  frontend/src/components/plp/PLPProductDisplay.tsx
  frontend/src/components/plp/PLPProductList.tsx
  frontend/src/components/plp/ProductsPLP.tsx
  frontend/src/pages/Chat/Chat.tsx
Labels: ✨ Feature, 🔨 Refactor, 우선순위: 🟠 높음, 🙋‍♂️ Question

#135 feat: 신발장 수정, 삭제 기능 구현
  frontend/src/apis/firebase/auth.ts
  frontend/src/apis/firebase/closetFirestore.ts
  frontend/src/components/shoeCloset/EmptyShoeCard.tsx
  frontend/src/components/shoeCloset/EmptyShoeComponent.tsx
  frontend/src/components/shoeCloset/ShoeClosetLoading.tsx
  frontend/src/components/shoeCloset/ShoeComponent.tsx
  frontend/src/components/shoeCloset/ShoeListComponent.tsx
  frontend/src/components/shoeCloset/details/ShoeClosetDetailInfo.tsx
  frontend/src/components/shoeCloset/details/ShoeClosetDetailLoading.tsx
  frontend/src/components/shoeCloset/details/ShoeClosetOptionMenu.tsx
  frontend/src/components/shoeCloset/register/RatingComponent.tsx
  frontend/src/components/shoeCloset/register/SelectedShoe.tsx
  frontend/src/components/shoeCloset/register/ShoeRegisterInputForm.tsx
  frontend/src/components/shoeCloset/search/SearchResultList.tsx
  frontend/src/pages/ShoeCloset/Review/Modify.tsx
  frontend/src/pages/ShoeCloset/Review/Review.tsx
  frontend/src/pages/ShoeCloset/SearchShoeCloset.tsx
  frontend/src/pages/ShoeCloset/ShoeCloset.tsx
  frontend/src/pages/ShoeCloset/ShoeClosetOverview.tsx
  frontend/src/router/index.tsx
  frontend/src/store/auth.store.ts
  frontend/src/types/product.d.ts
Labels: ✨ Feature, 🔨 Refactor, 우선순위: 🟠 높음

#139 신발장 컴포넌트, 페이지 네이밍, Router path 변경 및 기타 css 수정
  frontend/src/components/myshopping/LikedProducts.tsx
  frontend/src/components/myshopping/RecentProducts.tsx
  frontend/src/components/shoeCloset/AddShoeButton.tsx
  frontend/src/components/shoeCloset/EmptyShoeCard.tsx
  frontend/src/components/shoeCloset/EmptyShoeComponent.tsx
  frontend/src/components/shoeCloset/ShoeComponent.tsx
  frontend/src/components/shoeCloset/register/RatingComponent.tsx
  frontend/src/components/shoeCloset/register/RecomendSizeRadioGroup.tsx
  frontend/src/components/shoeCloset/register/SearchShoeButton.tsx
  frontend/src/components/sidemenu/SideMenu.tsx
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/pages/MyShopping/MyShopping.tsx
  frontend/src/pages/ShoeCloset/SearchShoeCloset.tsx
  frontend/src/pages/ShoeCloset/ShoeCloset.tsx
  frontend/src/pages/ShoeCloset/ShoeClosetAdd.tsx
  frontend/src/pages/ShoeCloset/ShoeClosetDetail.tsx
  frontend/src/pages/ShoeCloset/ShoeClosetModify.tsx
  frontend/src/router/index.tsx
Labels: 🎨 Html&css, 🐞 BugFix, 🔨 Refactor, 우선순위: 🟠 높음
