Repository StepUpper/stepup_front, pull requests merged in 2025-02, with the labels that each got.

#166 vite.congif.ts에 배포 시 console.log 및 debugger 자동 제거 설정 추가
  frontend/vite.config.ts
Labels: ⚙ Setting

#164 로그인 회원가입 수정
  frontend/src/apis/firebase/auth.ts
  frontend/src/components/Chat/ChatLoading.tsx
  frontend/src/components/common/html/DropDown.tsx
  frontend/src/components/common/html/Input.tsx
  frontend/src/components/login/Login.tsx
  frontend/src/components/signup/SignUpRequired.tsx
  frontend/src/styles/tailwind.css
Labels: 🔨 Refactor

#167 로그인, 회원가입 리팩토링과 배포 시 로그 제거
  frontend/src/apis/firebase/auth.ts
  frontend/src/components/Chat/ChatLoading.tsx
  frontend/src/components/common/html/DropDown.tsx
  frontend/src/components/common/html/Input.tsx
  frontend/src/components/login/Login.tsx
  frontend/src/components/signup/SignUpRequired.tsx
  frontend/src/styles/tailwind.css
  frontend/vite.config.ts
Labels: 🔨 Refactor

#168 로그인, 회원가입 리팩토링과 배포 시 로그 제거
  frontend/src/apis/firebase/auth.ts
  frontend/src/components/Chat/ChatLoading.tsx
  frontend/src/components/common/html/DropDown.tsx
  frontend/src/components/common/html/Input.tsx
  frontend/src/components/login/Login.tsx
  frontend/src/components/login/LoginBottomSheet.tsx
  frontend/src/components/signup/SignUp.tsx
  frontend/src/components/signup/SignUpRequired.tsx
  frontend/src/styles/tailwind.css
  frontend/vite.config.ts
Labels: 🔨 Refactor

#170 fix: 회원가입 import path 대소문자 에러 해결
  frontend/src/components/login/LoginBottomSheet.tsx
  frontend/src/components/signup/SignUp.tsx
Labels: 🐞 BugFix
